- name: variables
  hosts: local
  connection: local
  vars:   # Play level variables -- Global variables
    COURSE: "DevOps with AWS"
    DURATION: "120 hrs"
    TRAINER: Sivakumar
  tasks:
  - name: print the variable
    vars:   #Inside task variables for only that perticular task(Local variables)
      COURSE: Ansible
    ansible.builtin.debug:
      msg: "Course is {{COURSE}}, Duration is {{DURATION}}. Trainer is {{TRAINER}}"

      #Output: Course is Ansible
  
  - name: print the variable
    ansible.builtin.debug:
      msg: "Course is {{COURSE}}, Duration is {{DURATION}}. Trainer is {{TRAINER}}"

      #Output:here Course is DevOps with AWS