- name: check value is greater than 10 or not
  hosts: local
  connections: local
  vars:
    my_number: 15
  tasks:
  - name: print if number is greater than 15
    ansible.builtin.debug:
      msg: "Given number {{ my_number }} is greater than 15"
  when: my_number > 15

  - name: print if number is lessthan or equals to 15
    ansible.builtin.debug:
      msg: "Given number {{ my_number }} is lessthan or equals to 15"
  when: my_number <= 15